### ISSUE TITLE
ヘッダ情報カスタマイズ確認 twitter, facebook, note, ogタグ/image, google analytics

### ISSUE THREAD

**Issue by yukilab2** [CodeForNiigata/covid19#10]

**Comment by kasacchiful** [comment]
faviconも変更が必要ですね。

**Comment by kasacchiful** [comment]
対応が必要と思われる箇所:

- og:url
    - 本番サイトでも `https://dev-niigata-informal.netlify.com/` が固定されている
- og:image
    - URLがGitHubのリポジトリにあるファイルになっている
- twitter:site
    - `@tokyo_bousai` になっている
- twitter:creator
    - `@tokyo_bousai` になっている
- twitter:image
    - URLがGitHubのリポジトリにあるファイルになっている
- fb:app_id
    - 東京都のサイトと同じIDになっている
- canonical
    - `https://stopcovid19.metro.tokyo.lg.jp/` になっている

**Comment by kasacchiful** [comment]
対応案:

- og:url
    - 本番サイトのURLに変更
- og:image
    - 本番サイトのURLに変更
- twitter:site
    - @code4niigata に変更
- twitter:creator
    - @code4niigata に変更
- twitter:image
    - 本番サイトのURLに変更
- fb:app_id
    - Code for Niigataで新たにID取得して設定 or 何も設定しない
- canonical
    - 本番サイトのURLに変更
