### ISSUE TITLE
最新のお知らせの更新時間の表示について

### ISSUE THREAD

**Issue by michiyac4ngt** [CodeForNiigata/covid19#106]
13時以降に出ているお知らせの更新時間が11時台なので多分現状リンクしていないはず。
更新時間を適切に設定したい。
![image](https://user-images.githubusercontent.com/14312281/77177025-3c12d900-6b08-11ea-95af-e97e1d02e594.png)

**Comment by kasacchiful** [comment]
該当箇所の日時は `data/data.json` の `lastUpdate` の値が表示される。
ここの値が正しく設定できれば良さそう。

https://github.com/CodeForNiigata/covid19/blob/5c3049a664491e7a7b2f9592b63347621dad27a2/data/data.json#L1151-L1153

**Comment by circled9** [comment]
`tool/convert.php`を見た感じ、最新のお知らせではなくグラフのデータを基準にした日時を出しているようです。
見た感じ、各データの中で一番最新のものの日時 = 最終更新としているようです。
（PHP読める人、読んでくれると助かります...）

**Comment by kasacchiful** [comment]
そうですね。データの中で一番新しいものの日時を`lastUpdate`にしてそうですね。
このあたりで、`data/data.json` の `lastUpdate` の値を更新しているようです。

https://github.com/CodeForNiigata/covid19/blob/193956a79cdd8798709b007d125e6cce02d73eb6/tool/convert.php#L255-L276

ちなみに、`tool/convert.php`がコールされるタイミングってどんな時でしょうか。

**Comment by taka1985** [comment]
vueは読めないのですが、C#の感じで読みました。

■意見
convert.phpは今使っていない気がします。
data/data.jsonにあるlastUpdateを使っている気がします。

■理由
convert.php自体は最初に「require __DIR__.'/vendor/autoload.php';」とあるので
・venderフォルダーがないと思って気になったこと
・ビルド通らなそうと思ったこと
・convet.php内　下部にxlsxに関する記述がいくつか出てくるので、
　以前使っていたphpなのでは無いか、と推測。
　以下が出てきました。
　https://github.com/tokyo-metropolitan-gov/covid19/issues/355

⇒このissuesを見る限りでは、別にExcelがファイルがあるようで、
　それをjson形式に吐き出しをしていたのではないでしょうか。

**Comment by taka1985** [comment]
https://github.com/CodeForNiigata/covid19/commit/799eed76f36d017524ae232e561b8f2c2ad0b9a2#diff-868ae2d65fb52e0bf680b28558a92a88
たぶんもうクローズでよさそう。

**Comment by michiyac4ngt** [comment]
すみません、これ今の所手作業で直しているのでまだクローズできないです。
※忘れる！

**Comment by two-pack** [comment]
更新時間がstagingブランチの更新日時としてもよければ、stagingブランチのworkflowでdata/data.jsonのlastUpdateを現在日時で書き換えることで、更新は自動化できると思いましたが、どうでしょうか？

**Comment by two-pack** [comment]
PRを作成してみました。
確認用にトリガーするブランチだけ変えて動かしてみた結果、以下のような感じで動いています。
https://github.com/two-pack/covid19/actions/runs/87589704
