### ISSUE TITLE
新規リンクの作成（公共交通機関の状況）

### ISSUE THREAD

**Issue by asukaG** [CodeForNiigata/covid19#120]
## 起こっている問題 / The Problem
- 公共交通機関にも影響が出ているので、新規リンク（ページ？）の作成を行う

## 期待する見せ方・挙動 / Expected Behavior
新規のページとリンクを追加
- http://www.niigata-kotsu.co.jp
- http://www.niigata-kotsu.co.jp/~noriai/route-bus/info/gakkyu_200316-0406.html

- 表示するとしたら、当サイトについての上に表示？
![スクリーンショット 2020-03-21 17 27 45](https://user-images.githubusercontent.com/52248419/77222769-7d06fe00-6b99-11ea-9822-114560b863d7.png)

**Comment by kasacchiful** [comment]
#131 のように、新潟交通以外の公共交通機関からの情報が掲載されているので、
別ページもしくは別カードにリンクをまとめて掲載することにする。
