### ISSUE TITLE
最新のお知らせの件数について

### ISSUE THREAD

**Issue by michiyac4ngt** [CodeForNiigata/covid19#122]
## 件数について
現在は最新のお知らせに6件、3/17～21の5日分が表示されているが、一定のラインを決めて、それ以上はユーザーアクションで見れるといった形が良いかと。
![image](https://user-images.githubusercontent.com/14312281/77239959-d3b91a00-6c23-11ea-9a2c-91e9b6977c99.png)

**Comment by yukilab2** [comment]
[+ もっと見る] ボタンですかね。　県・市の数に関する情報は最新一つづつにしぼる。＋たとえば3/17の緊急対策の様な項目一つは出しておくにして。

**Comment by taka1985** [comment]
https://covid19-fukui.com/
こういうのが一番簡単ですかね。
他に飛ばしておく...

**Comment by taka1985** [comment]
こちらのissueも似ているけれど...
https://github.com/CodeForNiigata/covid19/issues/150

**Comment by taka1985** [comment]
https://stopcovid19.code4chiba.org/
こういう書き方もありますね

**Comment by taka1985** [comment]
どれにしましょうか。

**Comment by taka1985** [comment]
こんな感じの実装をすればよさげですかね？
https://qiita.com/dai_designing/items/595992521d28e586437d
