### ISSUE TITLE
【提案】陽性患者と、無症状陽性患者の違いを定義した方がよい

### ISSUE THREAD

**Issue by taka1985** [CodeForNiigata/covid19#128]
## ページ上の言葉の定義を記載した方がよい。
- 「陽性患者」とグラフ上に出てくるが、何を指すか曖昧かもしれない。

## この部分
![image](https://user-images.githubusercontent.com/4952193/77244388-aa19e600-6c57-11ea-8dd5-db69fa444903.png)

## そう思った理由
https://toyokeizai.net/sp/visual/tko/covid19/
![image](https://user-images.githubusercontent.com/4952193/77244431-0b41b980-6c58-11ea-861b-ee799250a2f2.png)
⇒これと同じかを検証必要に思う。

**Comment by taka1985** [comment]
新潟県庁のホームページに、どこかに説明書きがあるかも？

**Comment by circled9** [comment]
https://www.pref.niigata.lg.jp/sec/kenko/bukan-haien.html

こちらのページを見る限りでは、特に区別しているともしてないとも判断できないですね...

**Comment by circled9** [comment]
県の事例ごとのPDFを読むと陽性患者か無症状陽性患者かは区別がつきます。
ただ、それを自動化するのは厳しいです。

また、新潟県のページでも感染事例を一覧で表示しているPDFでは症状の有無に関わらず一律で患者として扱っています。

違いを明確化させるのではなく「陽性事例」とか「陽性者」に表現を変えて症状がある人ない人が両方含まれていても問題ない表現にする、あたりが落とし所でしょうか。

**Comment by taka1985** [comment]
難しそうですし、却下の方がよさそうですね。
