### ISSUE TITLE
【提案】グラフごとの情報源を明記した方がよい

### ISSUE THREAD

**Issue by taka1985** [CodeForNiigata/covid19#130]
## 改善詳細 / Details of Improvement
- 検査陽性者の状況、陽性患者数、陽性患者の属性、検査実施数、帰国者・接触者相談センターへの相談件数とあるが、データソース明記が必要。

## 理由
- 信憑性を高めるため。
- 新潟県内情報なのか、新潟県外情報を含むのか、判断ができない。

**Comment by taka1985** [comment]
出典は、ここですかね？
https://www.pref.niigata.lg.jp/sec/kenko/bukan-haien.html

**Comment by circled9** [comment]
はい、貼っていただいたURLからリンクされているPDFを元にしています。

全グラフ同一のページからリンクしているPDFを参考にしているので、どこかに一言「ここのデータを元にしています」と書くだけでもいいかもしれませんね。

**Comment by taka1985** [comment]
![image](https://user-images.githubusercontent.com/4952193/78254440-e2130a00-7530-11ea-8319-2f3fda2760d9.png)
ローカルでは、このような感じにしてみました。
vueを使うのが、初めてなので、セオリーの修正方法ではないかもしれませんが。。。
