### ISSUE TITLE
イベント中止の表を時系列順にしたい

### ISSUE THREAD

**Issue by asukaG** [CodeForNiigata/covid19#135]
## 改善詳細 / Details of Improvement
- 新型コロナウィルス感染症の拡大防止による新潟県内のイベント中止および変更について
- 現在はPDFでの公表となっている

## スクリーンショット / Screenshot
https://niigata-kankou.or.jp/image/document/article_file/298
![スクリーンショット 2020-03-23 22 28 56](https://user-images.githubusercontent.com/52248419/77321555-b4220e80-6d55-11ea-82f5-7c3801e85137.png)

## 期待する見せ方・挙動 / Expected behavior
- 時系列順に並べたい

**Comment by circled9** [comment]
covid19に組み込まないで、これ単独のアプリとして作っちゃいましょうかねぇ。

**Comment by two-pack** [comment]
2020/04/30 21:00時点では該当PDFは時系列になっているようです。
https://niigata-kankou.or.jp/image/document/article_file/298

**Comment by michiyac4ngt** [comment]
本サイトとしては対応しないということでIssueを閉じます。
