### ISSUE TITLE
最新のお知らせの一部を固定化項目にしたい

### ISSUE THREAD

**Issue by asukaG** [CodeForNiigata/covid19#150]
## 改善詳細 / Details of Improvement
- 最新のお知らせの一部が毎日日付更新される。
- 固定化項目としたい

## スクリーンショット / Screenshot
![スクリーンショット 2020-03-26 23 41 33](https://user-images.githubusercontent.com/52248419/77659879-f64c8980-6fbb-11ea-9f63-9a24fd962d0f.png)

## 期待する見せ方・挙動 / Expected behavior
- スクリーンショットのように、固定化項目にする

**Comment by asukaG** [comment]
新潟県防災局や新潟市危機管理防災局、厚労省など、情報があるTwitterアカウントをhtmlにして、別途に頁作成する事で、更新の手間が省けるので、それを行おうと思います。

**Comment by michiyac4ngt** [comment]
URLが固定されているので、最新のお知らせではなく別途関連リンクのページを作る方向にしたい。
今は新潟県と新潟市のサイトだが他の市町村のサイト、本サイトのグラフ等を利用いただいている関連リンクなどもあるとよい。
