### ISSUE TITLE
陽性患者数の表示について

### ISSUE THREAD

**Issue by michiyac4ngt** [CodeForNiigata/covid19#165]
現状は0人の場合更新がないため前日までの最終日でデータ更新されます。
![image](https://user-images.githubusercontent.com/14312281/77924170-54d87700-72de-11ea-95fb-9b6ef107ba92.png)
ここについて、0人の場合は0人になるように修正したい。

**Comment by taka1985** [comment]
これって、ひょっとして運用でカバーできています？

data.jsonの「patients_summary.data」に0人の時でも登録すればできそうですし、
最新のdata.jsonをみるとそうしているようなので...

**Comment by michiyac4ngt** [comment]
現状は手作業でデータ修正しています。
まだ残しておいてください。

**Comment by circled9** [comment]
今見たらv1はそうなってましたね...v2では直ったみたいでちゃんと0の行が自動で追加されていました。

https://github.com/circled9/covid19-data-niigata/commit/961911c9fe093dd7564f2704c9f360d65653d0e8#diff-72569d8b78dbbae853b740ade144b73c

**Comment by taka1985** [comment]
ということは、クローズしてもよさそう、
ということですかね？

**Comment by circled9** [comment]
更新をされている @michiyac4ngt さんに判断をお任せします 🙇

**Comment by michiyac4ngt** [comment]
本件、v2では問題なさそうなのでクローズします。手作業で修正入れる際は要注意で。
