### ISSUE TITLE
リンク・文言のIssue登録

### ISSUE THREAD

**Issue by michiyac4ngt** [CodeForNiigata/covid19#17]
## Twitter、GitHub、LINE、FBのリンク先検討
・Twiiterは県のものを引っ張ってくる場合明記がいる

### 案1
Twitter：（新潟県広報広聴課）https://twitter.com/Niigata_Press
GitHub：https://github.com/CodeForNiigata/covid19
LINE：なし
FB：（新潟県）公式は地域政策課なのでちょっと違う
（Code for Niigata）https://www.facebook.com/profile.php?id=1627331974204688&ref=br_rs

**Comment by michiyac4ngt** [comment]
新潟県防災局：https://twitter.com/Niigata_Bousai

**Comment by asukaG** [comment]
新潟市危機管理防災局：https://twitter.com/niigatacity_kib?s=20

**Comment by yukilab2** [comment]
3/18朝の現状です 
![image](https://user-images.githubusercontent.com/33612000/76911152-693a6e00-68f3-11ea-86f2-9d5ce87d7123.png)

**Comment by michiyac4ngt** [comment]
3/21の現状です
![image](https://user-images.githubusercontent.com/14312281/77177436-da06a380-6b08-11ea-9120-28aca6e244c6.png)
問題ないかと思いますがいかがでしょうか。

**Comment by taka1985** [comment]
私も良いと思います。

**Comment by michiyac4ngt** [comment]
本件他に反応もないのでクローズとします。
現状は3/21と変わってないです。
