### ISSUE TITLE
i18n terminal/console warning

### ISSUE THREAD

**Issue by yukilab2** [CodeForNiigata/covid19#185]
## 起こっている問題 / The Problem
- xxxx(できるだけ簡潔に/as concise as possible)

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/33612000/78416145-be031600-7661-11ea-8082-cb5d18bc5e5f.png)

起動ターミナル上でも同様のwarn が出ている

```

 WARN  [vue-i18n] Value of key '新潟県' is not a string!                                                                                              10:35:13


 WARN  [vue-i18n] Value of key '新潟県' is not a string! (repeated 0 times)                                                                           10:35:13


 WARN  [vue-i18n] Cannot translate the value of keypath '新潟県'. Use the value of keypath as default.                                                10:35:13


 WARN  [vue-i18n] Value of key '新型コロナウイルス感染症対策情報（産業労働分野）まとめ' is not a string!                                              10:35:13


 WARN  [vue-i18n] Value of key '新型コロナウイルス感染症対策情報（産業労働分野）まとめ' is not a string! (repeated 0 times)                           10:35:13


 WARN  [vue-i18n] Cannot translate the value of keypath '新型コロナウイルス感染症対策情報（産業労働分野）まとめ'. Use the value of keypath as default.


 WARN  [vue-i18n] Value of key '県からのお願い' is not a string!                                                                                      10:35:13

```

## 期待する見せ方・挙動 / Expected Behavior
- i18nに関するwarnの解消

## 起こっている問題の再現手段 / Steps to Reproduce
1. `yarn dev`

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by taka1985** [comment]
https://github.com/tokyo-metropolitan-gov/covid19/issues/2687
関連？

**Comment by taka1985** [comment]
ひょっとして、と思っていること。
i18nにたいして、jsonのキー値は英語じゃないといけないのではないか説

**Comment by taka1985** [comment]
そんな気が、すごくする。
https://www.shookuro.com/entry/2019/08/30/181143
だとすると、東京公式サイトというか派生開発分がすべてこれに当てはまる。

**Comment by taka1985** [comment]
localesフォルダー配下のjsonファイルをすべて読み込む仕様の様子。
その中に、$t('xxx')に対応する `xxx:"hoge"` がないと蹴る様子。

**Comment by taka1985** [comment]
修正をしました

**Comment by yukilab2** [comment]
参考： json キーは、ECMAScript-404にて " で括られたものあればなんでもOK とされているので、日本語で大丈夫です。(ref http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf section 9 : string および 6: Objects  )  

ただ、jsonを利用する実装側の不都合で日本語をうけつけない可能性はありますが、東京都などおおよそ翻訳で使っているので大丈夫でしょう。

**Comment by taka1985** [comment]
> 参考： json キーは、ECMAScript-404にて " で括られたものあればなんでもOK とされているので、日本語で大丈夫です。(ref http://www.ecma-international.org/publications/files/ECMA-ST/ECMA-404.pdf section 9 : string および 6: Objects )
> 
> ただ、jsonを利用する実装側の不都合で日本語をうけつけない可能性はありますが、東京都などおおよそ翻訳で使っているので大丈夫でしょう。

↑
昨夜いろいろ試した結果、確かにそうでした。
