### ISSUE TITLE
一般ユーザーからの改善提案受付

### ISSUE THREAD

**Issue by michiyac4ngt** [CodeForNiigata/covid19#188]
## 改善詳細 / Details of Improvement
- TOPページからの改善提案の受付フォームの追加
- NHKニュースではCode for NiigataのSNS等にという話を入れたが、一般ユーザーがIssueをもっと簡単に投稿するための手段が欲しい。

## スクリーンショット / Screenshot

なし

## 期待する見せ方・挙動 / Expected behavior
- サイトへの改善提案のフォームを作成し、リンクを追加する
- 可能ならSlackに投稿を飛ばす

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by taka1985** [comment]
@michiyac4ngt さん
こちらはひょっとしてクローズですか？

**Comment by michiyac4ngt** [comment]
本件クローズします。

**Comment by taka1985** [comment]
クローズいただき、ありがとうございました！
