### ISSUE TITLE
県内の交通・公共施設に関する資料の見直しが必要ではないか

### ISSUE THREAD

**Issue by taka1985** [CodeForNiigata/covid19#209]
## 改善詳細 / Details of Improvement
-先日の緊急事態宣言を受けて、都市部と遠方を結ぶ交通、県下の交通、公共施設に関する対策が変わったのではないか。

## 期待する見せ方・挙動 / Expected behavior
- 情報の棚卸しが必要と思う。

## 例
- 泉観光
http://www.izumi-group.jp/news/?id=106
- 県下の公共施設に関する情報
https://www.pref-lib.niigata.niigata.jp/?page_id=330
- 佐渡汽船
http://www.sado-bus.com/news/994/

**Comment by michiyac4ngt** [comment]
このあたりも必要？
越後交通
http://www.echigo-kotsu.co.jp/covid19_bus.html

頚城自動車
- 佐渡汽船連絡バス運休
http://www.marukei-g.com/files/libs/2644/202004150954594508.pdf

- 直江津駅前案内所閉鎖
http://www.marukei-g.com/files/libs/2648/202004181017147445.pdf

- 通学定期券払い戻し
http://www.marukei-g.com/files/libs/2654/202004221832272442.pdf
