### ISSUE TITLE
県内各地のテイクアウトマップのリンク

### ISSUE THREAD

**Issue by michiyac4ngt** [CodeForNiigata/covid19#248]
## 改善詳細 / Details of Improvement
- 各地のテイクアウトマップのリンクページを作る

## 期待する見せ方・挙動 / Expected behavior
- 見附市　http://www.city.mitsuke.niigata.jp/19491.htm
- 新潟市（にいがた情報）　http://gata21.jp/archives/82778685.html
など

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by two-pack** [comment]
PR作成しようと思います。
燕市と三条市のホームページから、以下のサイトが紹介されたので一緒に追加したいとおもいます。
* [つばめおうちでお店ごはん](https://www.instagram.com/tsubame_takeout/)
* [＃三条エール飯](https://sanjoyellmeshi.localinfo.jp/)

どういう基準でリンクに追加するかは考える必要がある気がしました。
