### ISSUE TITLE
トップページ上に、一部表現が日本語ではなく英語になってしまっている。

### ISSUE THREAD

**Issue by taka1985** [CodeForNiigata/covid19#259]
## 起こっている問題 / The Problem
一部の文章が英語になっている。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/4952193/80303661-80bb1f80-87ec-11ea-9775-a3a70b01953e.png)

## 期待する見せ方・挙動 / Expected Behavior
日本語で表示をしてほしい。

## 起こっている問題の再現手段 / Steps to Reproduce
ページを開く
https://niigata.stopcovid19.jp/

## きっかけ
https://github.com/CodeForNiigata/covid19/commit/0eda6a88cc6f958bd8f5b3b53ea0559a65ff4555#diff-bfc7fda8df09e3e9ec8810b8bff5bf77
こちらにて、ja.json側に英語が入った模様。
![image](https://user-images.githubusercontent.com/4952193/80303794-659cdf80-87ed-11ea-85cc-52cc844776f0.png)

## 動作環境・ブラウザ / Environment
- Windows
- Chrome

**Comment by NPoi** [comment]
確認しましたが、ちょっとおなか空いたので後ほど対応します。

**Comment by taka1985** [comment]
ありがとうございます。
私も行おうと思っていたのですが、作業を中止しました。

よろしくおねがいします。
（おなかがすいている中、すみません...)


assignerとかタグをつけられるのですね、
管理権限あると、色々できて素敵ですね。
