### ISSUE TITLE
検査数のデータが正しくない気がする

### ISSUE THREAD

**Issue by taka1985** [CodeForNiigata/covid19#274]
## 起こっている問題 / The Problem
検査実施数がでているが、累積を見ると
今日時点で２５８９件
しかし、同数になるはずの
以下検査件数一覧https://www.pref.niigata.lg.jp/sec/kenko/covid19.html
を見ると、２７７５件
最新のデータ数との不一致が見受けられる気がする

## スクリーンショット / Screenshot
![Screenshot_20200428-222034](https://user-images.githubusercontent.com/4952193/80494181-58285680-89a1-11ea-9de6-40ef94c04387.png)
![Screenshot_20200428-222048](https://user-images.githubusercontent.com/4952193/80494186-5a8ab080-89a1-11ea-91fc-6c62caee2926.png)

## 期待する見せ方・挙動 / Expected Behavior
- おそらく、左上に出てくる「検査実施数○○件」が誤っている

## 起こっている問題の再現手段 / Steps to Reproduce
1.以下をみる。
　https://niigata.stopcovid19.jp/

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / ■Android
- ■Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by michiyac4ngt** [comment]
@taka1985 さん
ご指摘ありがとうございます。
#266 でスクレイピングしたデータに一部不備があったため（4/24と4/24が混在）事象発生。
本日分　#272では問題ないことを確認しました。

最新のデータpdfとサイトの表記に差があったりすると発生するのですが、古い方似合わせるか少しでも新しい情報に合わせるかは別途検討が必要です。

**Comment by taka1985** [comment]
問題ない、ということでしたらクローズいたします。
