### ISSUE TITLE
development => master PR マージ時、last update の日付で develop - master 間でconflict

### ISSUE THREAD

**Issue by yukilab2** [CodeForNiigata/covid19#276]
## 障害
development => master PR マージ時、last update の日付で develop - master 間でconflictが発生しています。 最新の日付にすれば良いだけですが、developについてはlast updateを更新しなくても良いです。 master = deploy先においてだけ更新されれば。

## 改善詳細 / Details of Improvement
- development => master PR マージ時のコンフリクトの解消：手法未調査

## 期待する見せ方・挙動 / Expected behavior
- development => master PR マージ時、last update の conflictの手動解決なしにmergeできる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by two-pack** [comment]
解決案で思いついたものです。
1. developmentブランチではlastupdateを更新しない運用にする。
2. [update lastupdateアクション](https://github.com/CodeForNiigata/covid19/blob/development/.github/workflows/update_lastupdate.yml)の対象ブランチをdevelomentに変える。
   + データ更新もmasterへは必ずdevelomentブランチを経由する前提です。
   + すべてのコミットに対してアクションが実行されるときたなくなるので、data/data.jsonを更新した場合のみ実行するようにする必要があると思います。手法は未調査です。

**Comment by two-pack** [comment]
>    * すべてのコミットに対してアクションが実行されるときたなくなるので、data/data.jsonを更新した場合のみ実行するようにする必要があると思います。手法は未調査です。

pathsフィルタでdata/*の更新のみで発火させればできそうです。
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

2番目の案でよければ、検証してPR作成します。

**Comment by yukilab2** [comment]
お願いします！

**Comment by two-pack** [comment]
PR発行しました。
以下のブランチで、ブランチ名だけ変えて検証しています。
https://github.com/two-pack/covid19/tree/test-1
https://github.com/two-pack/covid19/actions?query=workflow%3A%22update+lastupdate%22
