### ISSUE TITLE
aboutに東京都が残っている

### ISSUE THREAD

**Issue by yukilab2** [CodeForNiigata/covid19#29]
## 起こっている問題 / The Problem
問い合わせ先が東京都

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/33612000/76880671-5e63e700-68bb-11ea-9107-ac5d406ef2f3.png)

## 期待する見せ方・挙動 / Expected Behavior
- Code For Niigataへ

## 起こっている問題の再現手段 / Steps to Reproduce
http://localhost:3000/about

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by michiyac4ngt** [comment]
その上部の記載にも東京都が残ってます。
![image](https://user-images.githubusercontent.com/14312281/76881580-b5b68700-68bc-11ea-95d6-f10421ed7985.png)

**Comment by michiyac4ngt** [comment]
免責事項もでした。
![image](https://user-images.githubusercontent.com/14312281/76881680-d8e13680-68bc-11ea-9d0e-d4e024c4d02b.png)

**Comment by asukaG** [comment]
データについては非表示が良い（新潟市のオープンデータにないため）
Githubリポジトリのリンクを東京 => 新潟へ

![スクリーンショット 2020-03-18 2 27 51](https://user-images.githubusercontent.com/52248419/76883938-39be3e00-68c0-11ea-8c18-047199ae42f4.png)
