### ISSUE TITLE
グラフ単位のシェアのサムネが東京都

### ISSUE THREAD

**Issue by michiyac4ngt** [CodeForNiigata/covid19#294]
## 起こっている問題 / The Problem
- 新型コロナウイルス対策サイトでグラフ単位のシェアをしたときにサムネが東京都

## スクリーンショット / Screenshot

![image](https://user-images.githubusercontent.com/14312281/80895536-037a3800-8d21-11ea-889a-2f98617f039c.png)

## 期待する見せ方・挙動 / Expected Behavior
- 次のリンクの対応を入れる、できれば自動化
　https://qiita.com/koi_zoom1/items/2dee42de683889871d1b

**Comment by two-pack** [comment]
自動化は[東京](https://github.com/tokyo-metropolitan-gov/covid19/blob/development/.github/workflows/ogp_builder.yml)と同じようにmasterに対するアクションで生成でよければすぐできそうです。
ちょっとやってみた感じでは新潟のもので生成できています。
https://github.com/two-pack/covid19/tree/ogp_build_test/static/ogp

ただ、static/ogpへ個別にコミットするようなことがあると、 #276 と同じ問題が発生します。
この方法でよければ、期待する見せ方で書かれているものと含めて、PR作成します。

**Comment by two-pack** [comment]
アクションの実行に5min以上かかっています。
https://github.com/two-pack/covid19/actions/runs/94363206

OGPで必ずしも最新状態のグラフが不要なら、手動で一度作成とシェア時の文言などの修正のみで、アクションはやめたほうが良いと思います。

**Comment by two-pack** [comment]
#297 のPRを作成しました。とりあえず、東京とでる状況を改善するというところまでで、OGP作成の自動化は含めないリクエストになっています。
このため、以下で記載のあるTwitterの場合のキャッシュ対応も含めていません。
https://qiita.com/koi_zoom1/items/2dee42de683889871d1b

**Comment by michiyac4ngt** [comment]
@two-pack さん
ご対応いただきありがとうございます。
ご指摘いただいていると通り自動化までは不要かと思います。
