### ISSUE TITLE
相談先を東京->新潟に変更する

### ISSUE THREAD

**Issue by michiyac4ngt** [CodeForNiigata/covid19#3]
# 相談先を東京->新潟に変更する

### 平日日中
各保健所の電話番号
https://www.fukushihoken.metro.tokyo.lg.jp/iryo/kansen/coronasodan.html
### 平日夜間
03-5320-4592

### 平日日中/夜間
各保健所の電話番号
https://www.pref.niigata.lg.jp/sec/kenko/corona-center.html
※【夜間緊急連絡先】は警備員室につながります。
　電話番号をお伝えいただき、担当から折り返し御連絡します。

### FAXの場合
以下様式にて対応
https://www.pref.niigata.lg.jp/uploaded/attachment/206773.docx

**Comment by michiyac4ngt** [comment]
## 新潟県新型コロナウイルス感染症コールセンター
受付時間	月曜日～金曜日（祝日除く） ８：30～17：00
受付電話番号	025-282-1754
※聴覚や言語に障害のある方には次の方法で受付をいたします。
ＦＡＸ：025-282-1640
メール：ngt130040@pref.niigata.lg.jp

**Comment by yukilab2** [comment]
印刷ボタン削除(SVG編集すぐできないため）

**Comment by yukilab2** [comment]
FAXの様式がdocx で ITスキルないと印刷することすら難しすぎる。載せる意味が少ない改善必要
保健所の電話番号も、他ページ行かないとみれないので不便
