### ISSUE TITLE
#287 で対応されたグラフの土日色が、一部対応されていない様子

### ISSUE THREAD

**Issue by taka1985** [CodeForNiigata/covid19#304]
## 起こっている問題 / The Problem
- #287 のうち、検査実施数だけ色が付いていない

## スクリーンショット / Screenshot
![Screenshot_20200506-145501](https://user-images.githubusercontent.com/4952193/81145150-aac0ce80-8fb0-11ea-8866-8f16d1aacd33.png)

## 期待する見せ方・挙動 / Expected Behavior
- issueによれば、色が付くはず

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://niigata.stopcovid19.jp/
2. 検査実施数　をみる

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / ■Android
- ■Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by two-pack** [comment]
検査実施数が、TimeStackBarChartを使用しているためのようです。
新潟では実質、県内の件数しか扱っていないようなので、積み上げのグラフでなくてよければ、他と同じくTimeBarChartを使えば良い気がします。
ただ、data.jsonでのデータの持ち方も修正する必要があります。
ちょっとやってみた感じは以下のようなイメージです。
![idea](https://user-images.githubusercontent.com/378981/81486147-da602700-928d-11ea-95aa-b90eb49808d7.png)
