### ISSUE TITLE
新型コロナウイルス感染症が心配なときに　の改善提案（対　東京都ページ）

### ISSUE THREAD

**Issue by taka1985** [CodeForNiigata/covid19#307]
## 改善詳細 / Details of Improvement
- 東京都のページとデザインで大きく乖離した。理由によっては合わせてはどうか。

## スクリーンショット / Screenshot
▼東京都版
![Screenshot_20200506-221353](https://user-images.githubusercontent.com/4952193/81181120-ee362f80-8fe6-11ea-9c05-4d15cc77308f.png)
▼新潟県版
![Screenshot_20200506-221232](https://user-images.githubusercontent.com/4952193/81181125-effff300-8fe6-11ea-9f18-8800980f6c96.png)

## 期待する見せ方・挙動 / Expected behavior
- 理由によっては、東京都ページに沿わせてはどうか

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by michiyac4ngt** [comment]
@taka1985 さん
新潟県のサイト（下記）の表記が変わっていないため
こちらのサイトで変更したとして、その内容を見て相談していただいた県民の方がいた場合、県としては受け付けていただけない可能性があります。
なので、県のサイトが更新してから合わせて修正対応が良いと思います。
https://www.pref.niigata.lg.jp/sec/kenko/corona-center.html
![image](https://user-images.githubusercontent.com/14312281/81305747-a92efd80-90b9-11ea-9136-eaaf68745bfe.png)

**Comment by taka1985** [comment]
> @taka1985 さん
> 新潟県のサイト（下記）の表記が変わっていないため
> こちらのサイトで変更したとして、その内容を見て相談していただいた県民の方がいた場合、県としては受け付けていただけない可能性があります。
> なので、県のサイトが更新してから合わせて修正対応が良いと思います。
> https://www.pref.niigata.lg.jp/sec/kenko/corona-center.html
> ![image](https://user-images.githubusercontent.com/14312281/81305747-a92efd80-90b9-11ea-9136-eaaf68745bfe.png)

@michiyac4ngt 
変わったみたいですね
![Screenshot_20200509-071420](https://user-images.githubusercontent.com/4952193/81453551-c8668180-91c4-11ea-967b-ba4b0c51f884.png)

**Comment by taka1985** [comment]
https://www.pref.niigata.lg.jp/site/shingata-corona/corona-center1109.html
最終的にリンクがこちらになった模様。

東京版のcovidページも、官公庁のページにとばすだけになっており、メンテナンスを考慮した様子。
https://stopcovid19.metro.tokyo.lg.jp/
https://www.fukushihoken.metro.tokyo.lg.jp/oshirase/corona_0401.html

**Comment by michiyac4ngt** [comment]
リンク先を新潟県のものに変更します
