### ISSUE TITLE
37.5度以上など記述のある https://niigata.stopcovid19.jp/flow の更新

### ISSUE THREAD

**Issue by yukilab2** [CodeForNiigata/covid19#315]
## 起こっている問題 / The Problem
- 5/7以前の相談判断基準になっている

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/33612000/81460331-a3333c80-91df-11ea-8b9a-7cfefca8d5fa.png)

## 期待する見せ方・挙動 / Expected Behavior
* 判定フローがだいぶ変わっているのでデザインから見直し必要。
* ちなみにもととなった東京都のフローも以前だいぶ違う。https://stopcovid19.metro.tokyo.lg.jp/flow#sydr

- 参考　県の内容別相談窓口：  https://www.pref.niigata.lg.jp/site/shingata-corona/
- 参考 県による疑わしい症状について： https://www.pref.niigata.lg.jp/sec/kenko/corona-center#shoujou

## 起こっている問題の再現手段 / Steps to Reproduce
https://niigata.stopcovid19.jp/flow

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by taka1985** [comment]
関連
#307 , #308

**Comment by taka1985** [comment]
https://www.pref.niigata.lg.jp/site/shingata-corona/corona-center1109.html
最終的にリンクがこちらになった模様。

東京版のcovidページも、官公庁のページにとばすだけになっており、メンテナンスを考慮した様子。
https://stopcovid19.metro.tokyo.lg.jp/
https://www.fukushihoken.metro.tokyo.lg.jp/oshirase/corona_0401.html


ということで、#307, #308 にも書いたのですが、
フローを書くのではなくて、情報統制の観点からも、新潟県のフロー図に飛ばすのが適切ではないか？

ご意見もとむ。
@yukilab2 さん, @michiyac4ngt さん

東京にて、flowページに対するこのようなissueもあり、消す方向のようにみえます
https://github.com/tokyo-metropolitan-gov/covid19/issues/6188

参考）
https://github.com/CodeForNiigata/covid19/issues/307#issuecomment-835119797
