### ISSUE TITLE
faviconが東京都の銀杏マーク

### ISSUE THREAD

**Issue by yukilab2** [CodeForNiigata/covid19#32]
## 起こっている問題 / The Problem
- ブラウザタブに表示される favicon.icoが東京都のになってる

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/33612000/76882072-75a3d400-68bd-11ea-9963-3d04cf65ccae.png)

## 期待する見せ方・挙動 / Expected Behavior
- favicon.icoがないか、新潟の何かに。

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kasacchiful** [comment]
とりあえず、現在の対策サイトで使われている、新潟県の地図の図形でfavicon作っておきます。

**Comment by kasacchiful** [comment]
#36 で対応されたので、closeします。
