### ISSUE TITLE
棒グラフのX軸の目盛りが2021年分ない

### ISSUE THREAD

**Issue by yukilab2** [CodeForNiigata/covid19#374]
## 起こっている問題 / The Problem
- 陽性患者数・検査実施数グラフの棒グラフ（縦棒）は正しく出ているが X軸のラベルが2021年分出ておらず、2020年分を引き伸ばして表示しているだけになっている。

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/33612000/110243007-e4c97b00-7f9b-11eb-91b3-df1901164d34.png)

## 期待する見せ方・挙動 / Expected Behavior
- X軸の日付に最近の  1月・2月・3月が追加されているべき

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://niigata.stopcovid19.jp/ を表示する

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by circled9** [comment]
@yukilab2 

#376 で修正されたのでcloseします。
対応ありがとうございました 🙏 

<img width="583" alt="陽性患者数" src="https://user-images.githubusercontent.com/5251092/111640956-0817e400-8840-11eb-9113-c00113c8d3fd.png">
