### ISSUE TITLE
データを取得・変換する

### ISSUE THREAD

**Issue by michiyac4ngt** [CodeForNiigata/covid19#4]
# 新潟県のコロナウイルスについて
https://www.pref.niigata.lg.jp/sec/kenko/bukan-haien.html

## ５ 県内における「帰国者・接触者相談センター」への相談件数及び検査件数
（１）帰国者・接触者相談センターへの相談件数
（２）検査件数

これらをサイトのデータ形式に変換する。
pdfなので、変換方法については別途検討（現時点の数なら手作業でも可能

**Comment by circled9** [comment]
「新潟県内の報告一覧表」も変換します。

今のところ、Google SpreadSheetに手で編集したデータをアプリのJSONに変換する方向で考えています。
若干undocumentedな使い方なのですが、SpreadSheetに対してCSVとしてアクセスできるURLが存在するので、そちらにPythonからアクセスしてJSONを生成します。

配布しているPDFをパースする方法も確立はしているのですが、アップロードされるフォーマットが必ず毎回同じではないのでちょっと自動化するのは厳しいかもしれません。
作成した翌日にいきなり一列減っててException吐きました 😩
