### ISSUE TITLE
提案：i18n json を google spread sheetから作成するスクリプト

### ISSUE THREAD

**Issue by yukilab2** [CodeForNiigata/covid19#46]
## 改善詳細 / Details of Improvement
- 課題：手編集で全角空白が入っている不具合があった。エラー除去が難しいので、編集は手でよいとして、json出力を自動化したい。 
- 仕様案 => https://github.com/CodeForNiigata/covid19/wiki/%E7%BF%BB%E8%A8%B3HELPER

仕様の合意から

## 動作環境・ブラウザ / Environment
python3

**Comment by ch-saeki** [comment]
はじめまして。
仕様案読ませていただきました、この仕様でひとまず問題なさそうに見えますので
script作成しようと思いますがいいでしょうか?
もし手を付けてよければ、以下情報いただけると嬉しいです。
・使い方はデータ更新用scriptと同じ感じでよい?
・対象spreadsheetは以下のファイル?
```
https://docs.google.com/spreadsheets/d/1hcU7fT2peAlKNH5Dcp9xufuXH4vf5FGsRKxcF9WC9zc/edit#gid=17066585
```
差分レポートの見せ方は実際に差分を取ってみてからでないとちょっとイメージ固まってないのですが、イメージあれば教えて下さい。

**Comment by yukilab2** [comment]
確認ありがとうございます。

使い方 => 特に拘っていません。最低限マニュアルで更新できればと。
spreadsheet => それです。
差分レポート => 想定はありません。まずはわかれば良いかと。

**Comment by taka1985** [comment]
私が知らなかっただけなのですが、
今後このスレッドを見た人にも分かるように...
I18N=International　: 国際化対応 の意味。要するに多言語化。

**Comment by ch-saeki** [comment]
情報ありがとうございます、ひとまず私のrepositoryで進行中です。
```
https://github.com/ch-saeki/covid19-i18n-helper-niigata
```

**Comment by ch-saeki** [comment]
ローカルでのリソースチェック、google spread sheetからのjson出力を実装しました。

**Comment by taka1985** [comment]
@yukilab2 さん, @ch-saeki さん
こちらって、クローズでよかったのでしょうか。
どうにも違和感があり、よくよく見返したのですが、本題が変わっていませんでしょうか？

■最初
・i18n jsonをつくるための、スクリプト生成

■結果
・クローズissueは以下だが、こちらの内容は
　「i18n jsonの更新」のみ。スクリプト生成はされていない模様。
　https://github.com/CodeForNiigata/covid19/pull/218/commits
・スクリプト生成は、
　https://github.com/CodeForNiigata/covid19/issues/46#issuecomment-602758103
　こちらにて進行

**Comment by NPoi** [comment]
@taka1985  んー、私はいいと思います。
covid19のレポジトリで、スクリプトまでは管理しないでいいと思っています。
Issueで課題という認識を皆がもったからといって、必ずしも、covid19レポジトリへの変更が必須というわけではないです。別のところで管理がなされていたり、またはサーバ設定などで、レポジトリの変更が伴わない変更だったりあり得ます（もちろん、そういったものを別途gitの管理対象にすることはありえるでしょうが、同一レポジトリで管理するか、別のレポジトリで管理するかは議論が必要でしょう）。

>　「i18n jsonの更新」のみ。スクリプト生成はされていない模様。

とありますが、実態としてスクリプトについては、k-sakekiさんが作成され、彼のレポジトリで管理が出来ているわけですし、
https://github.com/ch-saeki/covid19-i18n-helper-niigata
そこから吐き出された言語ファイルはcovid10側のバージョンによって依存性を持つので一緒に管理しなければなりませんが、それを生成するプログラム/スクリプトはそこまではcovid19でもつ必要はないように思います。

**Comment by NPoi** [comment]
https://github.com/ch-saeki/covid19-i18n-helper-niigata
のレポジトリを、CodeForNiigataグループで扱わせてもらう、とかであるのであればそれはそれで観点としてはあると思います。
