### ISSUE TITLE
README.mdにtokyoのリンクが残っている

### ISSUE THREAD

**Issue by yukilab2** [CodeForNiigata/covid19#54]
## 起こっている問題 / The Problem
- リンク誤り

## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/33612000/76960314-87898380-695e-11ea-98e1-2b9bf05d2791.png)

## 期待する見せ方・挙動 / Expected Behavior
- https://dev-niigata-informal.netlify.com/  に修正

**Comment by asukaG** [comment]
ブランチ修正しました

![スクリーンショット 2020-03-18 22 19 43](https://user-images.githubusercontent.com/52248419/76964831-abe95e00-6966-11ea-9a23-d719b84031ec.png)

**Comment by circled9** [comment]
@asukaG issueがreopenされてますが、何か問題ありましたか？

**Comment by asukaG** [comment]
あ、すいませんボタンミスだと思います。Closeします
