### ISSUE TITLE
popup linkがtokyoのまま

### ISSUE THREAD

**Issue by yukilab2** [CodeForNiigata/covid19#57]
## スクリーンショット / Screenshot
![image](https://user-images.githubusercontent.com/33612000/76962109-f0bec600-6961-11ea-8407-9e9a34a634ed.png)

## 期待する見せ方・挙動 / Expected Behavior
- LINE => 削除
- Twitter => 県、新潟市二つ載せる
- facebook => 削除

## 起こっている問題の再現手段 / Steps to Reproduce
1. https://dev-niigata-informal.netlify.com/にブラウザアクセス
2. グラフの右下の矢印をクリック

## 動作環境・ブラウザ / Environment
- macOS / Windows / Linux / iOS / Android
- Chrome / Safari / Firefox / Edge / Internet Explorer

**Comment by kasacchiful** [comment]
このリンクは、該当するカードの情報を各自のTwitter等に投稿するためのリンクだと思います。
リンクのURLは開発サーバになるので、現状の挙動でも問題ないと思われますが、いかがでしょう。

**Comment by kasacchiful** [comment]
もし修正する場合は components/DataView.vue を修正すれば良さそうです。

**Comment by yukilab2** [comment]
そうですね・・ 開発サーバと本番サーバで振り分けにしたいです。.env.development, .env.production から読み取れる様にすれば良さげですね。

**Comment by kasacchiful** [comment]
開発サーバと本番サーバで振り分けにしたいのであれば、location.host で指定されているから、稼働しているサーバのURLで、リンクのURL変わりそうです。特に変更しなくてもいいかも。

https://github.com/CodeForNiigata/covid19/blob/3dd47d841675070b7c770c1ef04a023d13f78088/components/DataView.vue#L143-L160

**Comment by yukilab2** [comment]
ありがとうございます！
