### ISSUE TITLE
当サイトについての問合わせ先リンクの修正

### ISSUE THREAD

**Issue by michiyac4ngt** [CodeForNiigata/covid19#67]
現状はConnpassのページに行っちゃうので適切なサイトに修正する
→会員登録等なしで、かんたんにアクセスできること

![image](https://user-images.githubusercontent.com/14312281/76970443-3766ed00-696f-11ea-849f-b8744cefad1c.png)

**Comment by kasacchiful** [comment]
とりあえずcodeforniigataのページに変更しておきますね。

**Comment by michiyac4ngt** [comment]
問い合わせフォームはこちらにもリンクしたほうが良さそう。
