### ISSUE TITLE
コールセンター電話番号が東京のまま

### ISSUE THREAD

**Issue by NPoi** [CodeForNiigata/covid19#77]
モバイル限定です。

https://niigata.stopcovid19.jp/flow をモバイル版で見た場合、番号が以下のようになっています。

![17239EFE-71AF-4D91-9EA5-3CA9716E3E3D](https://user-images.githubusercontent.com/1086012/77020324-b3d8ea80-69c6-11ea-93f3-659882d9b295.png)

**Comment by NPoi** [comment]
スマホからIssue登録するとテンプレート使わないので、書式合ってませんがご了承願います……

**Comment by yukilab2** [comment]
ですね。これ国じゃなくて東京都のでした（http://www.nms.ac.jp/hosp/news/_12026.html)

新潟のコールセンターはあるのでしょうか？　なければ各保健所？

**Comment by KanekoAtsuki** [comment]
新潟県のがあるので更新します

**Comment by NPoi** [comment]
すみません、もうプルリク投げちゃいました。

**Comment by yukilab2** [comment]
新潟県新型コロナウイルス感染症コールセンター に名前かえなくていいかな？ @NPoi 
ref : https://www.pref.niigata.lg.jp/sec/kikitaisaku/callsenter.html

**Comment by NPoi** [comment]
たしかに、そちらに変えた方が適切ですね。
ちょっと今触れないので、あとで対応します。

2020年3月19日(木) 13:19 yukilab <notifications@github.com>:
