### ISSUE TITLE
ビルドエラー

### ISSUE THREAD

**Issue by yukilab2** [CodeForNiigata/covid19#90]
## 起こっている問題 / The Problem
- ビルドしたときにエラーが出る。（事項可能なstaticファイルはできるけど）

## 起こっている問題の再現手段 / Steps to Reproduce

`yarn generate:deploy > deploy_build.log 2>&1
`

## 動作環境・ブラウザ / 
Environment
- macOS

`
yarn run v1.21.1
$ cross-env NODE_ENV=production nuxt-ts generate
start Loading module

 ERROR  Webpack mode only works with build.extractCSS set to *true*. Either extract your CSS or use 'postcss' mode

.....

[1m[33mWARNING in ./components/flow/FlowPc.vue?vue&type=style&index=0&module=true&lang=scss& (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-0-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-0-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-0-3!./node_modules/vuetify-loader/lib/loader.js??ref--19-0!./node_modules/vue-loader/lib??vue-loader-options!./components/flow/FlowPc.vue?vue&type=style&index=0&module=true&lang=scss&)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(1:352) grid-gap only works if grid-template(-areas) is being used or both rows and columns have been declared and cells have not been manually placed inside the explicit grid
 @ ./components/flow/FlowPc.vue?vue&type=style&index=0&module=true&lang=scss& (./node_modules/vue-style-loader??ref--7-oneOf-0-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-0-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-0-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-0-3!./node_modules/vuetify-loader/lib/loader.js??ref--19-0!./node_modules/vue-loader/lib??vue-loader-options!./components/flow/FlowPc.vue?vue&type=style&index=0&module=true&lang=scss&) 4:14-454
 @ ./components/flow/FlowPc.vue?vue&type=style&index=0&module=true&lang=scss&
 @ ./components/flow/FlowPc.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vuetify-loader/lib/loader.js??ref--19-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/flow.vue?vue&type=script&lang=js&
 @ ./pages/flow.vue?vue&type=script&lang=js&
 @ ./pages/flow.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js[39m[22m

[1m[33mWARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets: 
  fonts/a1a0ed8.eot (824 KiB)
  fonts/7fb0e37.woff2 (270 KiB)
  fonts/63d2a59.woff (382 KiB)
  fonts/fe1545e.ttf (824 KiB)
  f14fec4b173c7d7cc712.js (651 KiB)[39m[22m

....

[1m[33mWARNING in ./components/flow/FlowPc.vue?vue&type=style&index=0&module=true&lang=scss& (./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-0-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-0-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-0-3!./node_modules/vuetify-loader/lib/loader.js??ref--19-0!./node_modules/vue-loader/lib??vue-loader-options!./components/flow/FlowPc.vue?vue&type=style&index=0&module=true&lang=scss&)
Module Warning (from ./node_modules/postcss-loader/src/index.js):
Warning

(1:352) grid-gap only works if grid-template(-areas) is being used or both rows and columns have been declared and cells have not been manually placed inside the explicit grid
 @ ./components/flow/FlowPc.vue?vue&type=style&index=0&module=true&lang=scss& (./node_modules/vue-style-loader??ref--7-oneOf-0-0!./node_modules/css-loader/dist/cjs.js??ref--7-oneOf-0-1!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--7-oneOf-0-2!./node_modules/sass-loader/dist/cjs.js??ref--7-oneOf-0-3!./node_modules/vuetify-loader/lib/loader.js??ref--19-0!./node_modules/vue-loader/lib??vue-loader-options!./components/flow/FlowPc.vue?vue&type=style&index=0&module=true&lang=scss&) 4:14-454
 @ ./components/flow/FlowPc.vue?vue&type=style&index=0&module=true&lang=scss&
 @ ./components/flow/FlowPc.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vuetify-loader/lib/loader.js??ref--19-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/flow.vue?vue&type=script&lang=js&
 @ ./pages/flow.vue?vue&type=script&lang=js&
 @ ./pages/flow.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/server.js
 @ multi ./.nuxt/server.js[39m[22m
ℹ Generating pages

 ERROR   /cards/number-of-reports-to-covid19-telephone-advisory-center

TypeError: Cannot read property 'transition' of undefined
    at a.displayInfo (bb45eb6a4a7ad38d3e10.js:1:20122)
    at a.displayInfo (/Users/yukilab/temp/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:29698)
    at fn (bb45eb6a4a7ad38d3e10.js:1:22517)
    at Object.r [as infoPanel] (/Users/yukilab/temp/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:15508)
    at a.<anonymous> (bb45eb6a4a7ad38d3e10.js:1:14071)
    at a.t._render (/Users/yukilab/temp/covid19/node_modules/vue/dist/vue.runtime.common.prod.js:6:35273)
    at /Users/yukilab/temp/covid19/node_modules/vue-server-renderer/build.prod.js:1:70665
    at Yi (/Users/yukilab/temp/covid19/node_modules/vue-server-renderer/build.prod.js:1:67229)
    at io (/Users/yukilab/temp/covid19/node_modules/vue-server-renderer/build.prod.js:1:70641)
    at ro (/Users/yukilab/temp/covid19/node_modules/vue-server-renderer/build.prod.js:1:70272)
    at eo (/Users/yukilab/temp/covid19/node_modules/vue-server-renderer/build.prod.js:1:67519)
    at /Users/yukilab/temp/covid19/node_modules/vue-server-renderer/build.prod.js:1:70739
    at Yi (/Users/yukilab/temp/covid19/node_modules/vue-server-renderer/build.prod.js:1:67229)
    at io (/Users/yukilab/temp/covid19/node_modules/vue-server-renderer/build.prod.js:1:70641)
    at ro (/Users/yukilab/temp/covid19/node_modules/vue-server-renderer/build.prod.js:1:70272)
    at _t.eo [as renderNode] (/Users/yukilab/temp/covid19/node_modules/vue-server-renderer/build.prod.js:1:67519)

✔ Generated /parent
✔ Generated /about
✔ Generated /worker
✔ Generated /flow
✔ Generated /
✔ Generated /print/flow
✔ Generated /cards/details-of-confirmed-cases
✔ Generated /cards/attributes-of-confirmed-cases
✔ Generated /cards/number-of-tested
✔ Generated /cards/number-of-confirmed-cases
✔ Generated /cards/number-of-reports-to-covid19-consultation-desk
✔ Generated /cards/agency
✔ Generated /cards/predicted-number-of-toei-subway-passengers

 ERROR  Error generating /en/cards/details-of-confirmed-cases
 ERROR  Error generating /ko/cards/details-of-confirmed-cases
 ERROR  Error generating /zh-tw/cards/details-of-confirmed-cases
 ERROR  Error generating /zh-cn/cards/details-of-confirmed-cases
 ERROR  Error generating /ja-basic/cards/details-of-confirmed-cases
 ERROR  Error generating /en/cards/attributes-of-confirmed-cases
 ERROR  Error generating /en/cards/number-of-confirmed-cases
 ERROR  Error generating /en/cards/agency
 ERROR  Error generating /en/cards/number-of-reports-to-covid19-consultation-desk
 ERROR  Error generating /zh-cn/cards/number-of-tested
 ERROR  Error generating /en/cards/number-of-tested
 ERROR  Error generating /en/cards/predicted-number-of-toei-subway-passengers
 ERROR  Error generating /zh-cn/cards/number-of-reports-to-covid19-telephone-advisory-center
 ERROR  Error generating /zh-cn/cards/attributes-of-confirmed-cases
 ERROR  Error generating /en/cards/number-of-reports-to-covid19-telephone-advisory-center
 ERROR  Error generating /zh-tw/cards/number-of-confirmed-cases
 ERROR  Error generating /zh-cn/cards/number-of-reports-to-covid19-consultation-desk
 ERROR  Error generating /zh-cn/cards/number-of-confirmed-cases
 ERROR  Error generating /zh-tw/cards/number-of-tested
 ERROR  Error generating /zh-cn/cards/predicted-number-of-toei-subway-passengers
 ERROR  Error generating /zh-tw/cards/attributes-of-confirmed-cases
 ERROR  Error generating /zh-cn/cards/agency
 ERROR  Error generating /zh-tw/cards/number-of-reports-to-covid19-consultation-desk
 ERROR  Error generating /ko/cards/number-of-tested
 ERROR  Error generating /zh-tw/cards/number-of-reports-to-covid19-telephone-advisory-center
 ERROR  Error generating /ko/cards/predicted-number-of-toei-subway-passengers
 ERROR  Error generating /ko/cards/number-of-confirmed-cases
 ERROR  Error generating /ko/cards/attributes-of-confirmed-cases
 ERROR  Error generating /ko/cards/agency
 ERROR  Error generating /zh-tw/cards/agency
 ERROR  Error generating /ko/cards/number-of-reports-to-covid19-telephone-advisory-center
 ERROR  Error generating /ja-basic/cards/number-of-tested
 ERROR  Error generating /ja-basic/cards/number-of-confirmed-cases
 ERROR  Error generating /zh-tw/cards/predicted-number-of-toei-subway-passengers
 ERROR  Error generating /ja-basic/cards/attributes-of-confirmed-cases
 ERROR  Error generating /ja-basic/cards/agency
 ERROR  Error generating /ja-basic/cards/predicted-number-of-toei-subway-passengers
 ERROR  Error generating /ja-basic/cards/number-of-reports-to-covid19-telephone-advisory-center
 ERROR  Error generating /ja-basic/cards/number-of-reports-to-covid19-consultation-desk
 ERROR  Error generating /ko/cards/number-of-reports-to-covid19-consultation-desk
`

**Comment by circled9** [comment]
その部品がデータがないのを想定してないこと、そして新潟にはそのデータがないことが原因ですね。

トップからその部品を消したのですが、その部品単体のページがあることを見落としていました。

修正します。
